name: 3d-portfolio

on:
  push:
    branches:
      - main
      - development

  pull_request:
    types: [opened, synchronize]

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Prettier
        run: npm run format:fix

      - name: Run eslint
        run: npm run lint
